import { ExternalLink, MapPinned } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { buildMapsUrl, loadOpenStreetMap, toLatLngLiteral } from '../utils/googleMaps.js';

export default function OpenStreetMapRoute({ origin, destination, originLabel, destinationLabel }) {
  const node = useRef(null); const map = useRef(null); const [error, setError] = useState(''); const mapsUrl = buildMapsUrl(originLabel, destinationLabel);
  useEffect(() => { let active = true; let line; loadOpenStreetMap().then(async(L) => { if (!active || !node.current) return; const start = toLatLngLiteral(origin); const end = toLatLngLiteral(destination); const center = start || end || { lat: 37.7749, lng: -122.4194 }; map.current = L.map(node.current).setView([center.lat, center.lng], start && end ? 12 : 11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map.current); if (start) L.circleMarker([start.lat, start.lng], { radius: 8 }).addTo(map.current); if (end) L.circleMarker([end.lat, end.lng], { radius: 8 }).addTo(map.current); if (start && end) { try { const response = await fetch(`https://router.project-osrm.org/route/v1/driving/${start.lng},${start.lat};${end.lng},${end.lat}?overview=full&geometries=geojson`); const data = await response.json(); if (!response.ok || !data.routes?.[0]) throw new Error(); if (!active) return; line = L.geoJSON(data.routes[0].geometry, { style: { color: '#2563eb', weight: 5 } }).addTo(map.current); map.current.fitBounds(line.getBounds(), { padding: [24, 24] }); } catch { if (active) setError('Route preview is unavailable.'); } } }).catch(() => { if (active) setError('Map display is unavailable.'); }); return () => { active = false; if (map.current) { map.current.remove(); map.current = null; } }; }, [origin, destination]);
  return <div className="route-map-panel"><div ref={node} className="route-map-canvas" aria-label="OpenStreetMap route map"/>{error && <div className="state-bar danger">{error}</div>}<a className="map-fallback" href={mapsUrl} target="_blank" rel="noreferrer"><MapPinned size={22}/>Open route in Maps<ExternalLink size={16}/></a></div>;
}
